# This is the workflow for the CI pipeline
# It will run on every push to the development branch
# It will also run on every pull request to the development branch

name: .NET

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  validate_backend:
    name: validate backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./DLS2
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./DLS2
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./DLS2
        
  validate_doctor_frontend:
    name: validate doctor frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./DoctorUI
      - name: Build
        run: npm run build
        working-directory: ./DoctorUI
        
  validate_patient_frontend:
    name: validate patient frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./PatientUI
      - name: Build
        run: npm run build
        working-directory: ./PatientUI
